openapi: 3.1.1
info:
  title: "Auction API"
  description: "Synchronous API specification for the PITAS auction house"
  version: "1.1"
  license:
    name: "GPL-3.0-only"
    url: "https://opensource.org/license/gpl-3-0"

servers:
  - url: "https://app.${PUB_IP}.asse.scs.unisg.ch"
    description: Remote Development
  - url: "http://localhost:8090/"
    description: Local Development

tags:
  - name: Auctions
    description: Auction management endpoints. From the perspective of an auctioneer.
  - name: Bidders
    description: Bidder management endpoints. From the prespective of a bidder.
  - name: Discovery
    description: Discovery endpoints for finding other auction houses.

paths:
  /auctions:
    get:
      tags:
        - Auctions
      summary: Retrieve open auctions
      description: Retrieve a list of all open auctions from this group
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuctionListPayload"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /auctions/{auctionId}:
    get:
      tags:
        - Auctions
      summary: Retrieve auction
      description: Retrieve one auction
      parameters:
        - name: auctionId
          in: path
          required: true
          description: Unique identifier of the auction
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuctionPayload"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /auctions/{auctionId}/job:
    post:
      tags:
        - Auctions
      summary: Job executed
      description: The bid for a specific auction was won. The auctionId is specified in the request body
      parameters:
        - name: auctionId
          in: path
          required: true
          description: Unique identifier of the auction
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobPayload"
      responses:
        "201":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobPayload"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /auctions/{auctionId}/bid:
    post:
      tags:
        - Auctions
      summary: Place bid for auction
      description: Place a new bid for the specified auction. The auctionId is specified in the request body.
      parameters:
        - name: auctionId
          in: path
          required: true
          description: Unique identifier of the auction
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BidPayload"
      responses:
        "201":
          description: Bid placed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BidPayload"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /bidders:
    post:
      tags:
        - Bidders
      summary: Auction started
      description: Notification from other group that a new auction started
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuctionPayload"
      responses:
        "201":
          description: Auction created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuctionPayload"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /bidders/{auctionId}/job:
    post:
      tags:
        - Bidders
      summary: Bid for auction won
      description: The bid for a specific auction was won. The auctionId is specified in the request body
      parameters:
        - name: auctionId
          in: path
          required: true
          description: Unique identifier of the auction
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobPayload"
      responses:
        "201":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobPayload"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /discovery:
    get:
      tags:
        - Discovery
      summary: Retrieve known auction houses
      description: |
        Retrieve a list of known auction houses for the specified group type.
        Returns an object containing the group type and a list of auction house URIs.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveryHostsPayload"
              example:
                version: 1
                data:
                  type: "EVEN"
                  hosts:
                    - auctionHouseUri: "https://app.192.168.1.10.asse.scs.unisg.ch"
                    - auctionHouseUri: "https://app.192.168.1.20.asse.scs.unisg.ch"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      tags:
        - Discovery
      summary: Register auction house
      description: |
        Register this auction house with the discovery service.
        Allows a group to announce itself to the discovery overlay.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DiscoveryRegistrationPayload"
            example:
              version: 1
              data:
                type: "ODD"
                auctionHouseUri: "https://app.192.168.1.30.asse.scs.unisg.ch"
      responses:
        "201":
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveryRegistrationPayload"
              example:
                version: 1
                data:
                  type: "ODD"
                  auctionHouseUri: "https://app.192.168.1.30.asse.scs.unisg.ch"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    PayloadBase:
      type: object
      required:
        - version
        - data
      properties:
        version:
          type: integer
          description: API version carried in the payload
          example: 1
        data:
          type: object
          description: Domain data for this payload

    AuctionPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Auction"

    BidPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Bid"

    JobPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Job"

    AuctionListPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              type: object
              properties:
                auctions:
                  type: array
                  items:
                    $ref: "#/components/schemas/Auction"
    ErrorPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Error"

    DiscoveryHostsPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/DiscoveryHosts"

    DiscoveryRegistrationPayload:
      allOf:
        - $ref: "#/components/schemas/PayloadBase"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/DiscoveryRegistration"

    DiscoveryHosts:
      type: object
      required:
        - type
        - hosts
      properties:
        type:
          type: string
          enum: [EVEN, ODD]
          description: Group type identifier
          example: "EVEN"
        hosts:
          type: array
          items:
            $ref: "#/components/schemas/DiscoveryHost"
          description: List of discovered auction house URIs

    DiscoveryRegistration:
      type: object
      required:
        - type
        - auctionHouseUri
      properties:
        type:
          type: string
          enum: [EVEN, ODD]
          description: Group type identifier
          example: "ODD"
        auctionHouseUri:
          type: string
          format: uri
          description: URI of the auction house being registered
          example: "https://app.192.168.1.30.asse.scs.unisg.ch"

    DiscoveryHost:
      type: object
      required:
        - auctionHouseUri
      properties:
        auctionHouseUri:
          type: string
          format: uri
          description: URI of a discovered auction house
          example: "https://app.192.168.1.10.asse.scs.unisg.ch"

    Auction:
      type: object
      required:
        - status
        - auctionHouseUri
        - jobType
        - deadline
      properties:
        status:
          type: string
          enum: [OPEN, CLOSED]
          description: Current status of the auction
        auctionId:
          type: string
          format: uuid
          description: ID of the auction, used to reference it in further requests
          example: 83a6bdbd-dcf5-43ad-a476-5d43de8285ea
        auctionHouseUri:
          type: string
          format: uri
          description: URI of the auction house hosting the auction
          example: "https://group12.pitas.scs.unisg.ch:8080/"
        jobType:
          type: string
          description: JobType for the auction
        deadline:
          type: string
          format: date-time
          description: Deadline for bidding in this auction
          example: "2025-11-30T16:42:12.69Z"

    Bid:
      type: object
      required:
        - bidderName
        - bidderAuctionHouseUri
      properties:
        auctionId:
          type: string
          format: uuid
          description: ID of the auction this bid is for
          example: 83a6bdbd-dcf5-43ad-a476-5d43de8285ea
        bidderName:
          type: string
          description: Name of the bidding group
          example: "group42"
        bidderAuctionHouseUri:
          type: string
          format: uri
          description: URI of the bidders auction house, used to assign job

    Job:
      type: object
      required:
        - auctionId
        - jobType
        - status
      properties:
        auctionId:
          type: string
          format: uuid
          description: ID of the auction this job is from
          example: 83a6bdbd-dcf5-43ad-a476-5d43de8285ea
        auctionHouseUri:
          type: string
          format: uri
          description: URI of the auction house hosting the auction
          example: "https://group12.pitas.scs.unisg.ch:8080/"
        jobType:
          type: string
          description: Job type
        status:
          type: string
          enum: [OPEN, EXECUTED, FAILED]
        inputData:
          type: string
          description: Optional input data for job
        outputData:
          type: string
          description: "Result of job: result of job if status EXECUTED, error message if status FAILED"

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorPayload"
          example:
            version: 1
            data:
              message: "Invalid input data"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorPayload"
          example:
            version: 1
            data:
              message: "Resource not found"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorPayload"
          example:
            version: 1
            data:
              message: "An unexpected error occurred"
