FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY test_discovery.py .

ENV AUCTION_HOUSE_BASE_URL=http://localhost:8090
ENV TEST_CLIENT_URI=http://localhost:8092
ENV GROUP_TYPE=EVEN

CMD ["python", "test_discovery.py"]
